### PR TITLE
Feature: data upload

### PR DESCRIPTION
**Pull request by honmanyau**
A route implemented using `Express.Router()` for uploading new data was implemented. This route requires an environment variable called `UPLOAD_SECRET` to match the `password` URL query string for `/data.json` to be replaced by the file uploaded.

### CODE REVIEW

**Comment by RandellDawson** [comment]
Can we review the changes on this PR together?

**Comment by honmanyau** [comment]
I think we can probably close this one because of the migration—some of the files have been moved over. If we still need the route for handling data upload in the short term, I can submit another PR to the new repository, what do you think? :)

**Comment by RandellDawson** [comment]
I still would like to try to implement the upload feature right now, to keep update the data.json file on Glitch from my pc which I can set up on a scheduler.

**Comment by honmanyau** [comment]
Okay! In that case the route is already set up to do that—when a file is POST-ed to it, then file will be renamed to `../data.json` (effectively replacing it). Something similar to the following could then be used to upload a file:

```javascript
const fetch = require('node-fetch');
const FormData = require('form-data');

// ...

const formData = new FormData();
  
formData.append('file', fs.createReadStream(__dirname + '/data.json'));
fetch('https://foamy-block.glitch.me/upload', {
    method: 'POST',
    body: formData
});
```

The only other thing that needs to be done is setting up a password to work with it. If it sounds reasonable I can submit a PR for the server side of it some time today!

**Comment by RandellDawson** [comment]
So right now, only the foamy-bloc.glitch.me/upload works?  Correct?  

When you say PR for server side, you mean on the mono repo?  That sounds good.  Then, once we get that up and running, we can start designing the Mongo db, so we can stop using the data.json file served from Glitch.

**Comment by honmanyau** [comment]
Yes with regard to the test Glitch; although the one submitted with commit [d6bd4a7](https://github.com/RandellDawson/pr-relations/pull/21/commits/d6bd4a78f85a8bf1dc7b7d37bc9cb37ac255b43e) is slightly more sophisticated (checks for a secret in the environment variables and paths are wired up correctly as far as I can tell).

And also yes to the mono-repo—I will have a bit of a think and do some tests before I submit the PR!

**Comment by honmanyau** [comment]
I had a bit of a think about this again; given that this repo will likely be archived, I think we can merge both this and PR #20 (for completeness), or just close them particularly if minimal changes will be made even before the code in the monorepo goes into production (I'm not fussed either way).

I will still implement the `/upload` route today after testing and double-checks on a remix, and provide a script for uploading data locally!

**Comment by honmanyau** [comment]
I am closing this PR because this one has also been incorporated into the monorepo!

**Pull request closed without merging**
